language: objective-c
osx_image: xcode9
script:
    - xcodebuild clean test -project Calculator/Calculator.xcodeproj -scheme Calculator -destination 'platform=iOS Simulator,OS=11.0,name=iPhone 6' -quiet
    
    